name: 'Seller'
type: profile
description: 'Install Seller drupal store.'
# version: VERSION
# core: 8.x
# Un comment to completely remove profile selection.
#distribution: TRUE

# Information added by Drupal.org packaging script on 2016-05-05
version: '8.x-1.3'
core: '8.x'
project: 'config_installer'
datestamp: 1462466940
